<?xml version="1.0"?>
<robot name="simple_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find simple_robot_description)/urdf/simple_robot.gazebo.xacro"/>


  <xacro:property name="width" value="0.18" />
  <xacro:property name="length" value="0.25" />
  <xacro:property name="height" value="0.2" />
  <xacro:property name="caster_dia" value="0.02" />
  <xacro:property name="wheel_dia" value="0.064" />
  <xacro:property name="wheel_len" value="0.025" />
  <xacro:property name="wheel_separation" value="0.22" />
  <xacro:property name="lidar_h" value="0.05" />
  <xacro:property name="lidar_dia" value="0.07" />
  <xacro:property name="update_rate" value="30" />

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <!-- inertia -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${1*mass}" ixy="0.0" ixz="0.0" iyy="${1*mass}" iyz="0.0" izz="${1*mass}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertial" params="m x y z">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
        iyy="${m*(x*x+z*z)/12}" iyz = "0"
        izz="${m*(x*x+z*z)/12}"
      />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
      izz="${m*r*r/2}"
      />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
        iyy="${2*m*r*r/5}" iyz = "0"
        izz="${2*m*r*r/5}"
      />
    </inertial>
  </xacro:macro>

<!-- base_footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${height/2+wheel_dia/2}"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${height/2+wheel_dia/2}"/>
    </collision>
    <xacro:box_inertial m="10" x="${length}" y="${width}" z="${height}"/>
  </link>



  <!-- imu -->
  <link name="imu_link"/>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${wheel_dia/2+height/2}"/>
  </joint>

  <!-- lidar -->
  <link name="base_scan">
    <visual>
      <geometry>
        <cylinder length="${lidar_h}" radius="${lidar_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lidar_h}" radius="${lidar_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m=".3" r="${lidar_dia/2}" h="${lidar_h}"/>
  </link>
  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin rpy="0 0 0" xyz="0 0 ${wheel_dia/2+height+lidar_h/2}"/>
  </joint>
  <gazebo reference="base_scan">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- caster wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
   <xacro:sphere_inertia m=".01" r="${wheel_dia/2}"/>
  </link>
  <joint name="base_to_caster_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin rpy="0 0 0" xyz="-${length/2-caster_dia/2} 0 ${wheel_dia/2}"/>
  </joint>

<!-- wheel -->
  <xacro:macro name="wheel" params="prefix reflect">

    <link name="wheel_${prefix}_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_dia/2}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_dia/2}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m=".3" r="${wheel_dia/2}" h="${wheel_len}"/>
    </link>
    <joint name="wheel_${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="wheel_${prefix}_link"/>
      <axis xyz="0 0 -1"/>
      <origin rpy="1.5708 0 0" xyz="0.03 ${wheel_separation/2*reflect} ${wheel_dia/2}"/>
    </joint>

    <gazebo reference="wheel_${prefix}_link">
      <mu1>10.1</mu1>
      <mu2>10.1</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>0.1</maxVel>
      <fdir1>1 0 0</fdir1>
      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <!-- <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="wheel_${prefix}_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission> -->
    
  </xacro:macro>

  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>

</robot>
