<?xml version="1.0"?>
<robot name="simple_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.18" />
  <xacro:property name="length" value="0.25" />
  <xacro:property name="hight" value="0.2" />
  <xacro:property name="caster_dia" value="0.02" />
  <xacro:property name="wheel_dia" value="0.064" />
  <xacro:property name="wheel_len" value="0.025" />
  <xacro:property name="wheel_separation" value="0.22" />

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${1*mass}" ixy="0.0" ixz="0.0" iyy="${1*mass}" iyz="0.0" izz="${1*mass}" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${length} ${width} ${hight}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${hight/2+wheel_dia/2}"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${length} ${width} ${hight}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${hight/2+wheel_dia/2}"/>
    </collision>
    <xacro:default_inertial mass="20"/>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_dia/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:default_inertial mass="0.01"/>
  </link>

  <joint name="base_to_caster_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin rpy="0 0 0" xyz="-${length/2-caster_dia/2} 0 ${wheel_dia/2}"/>
  </joint>

  <gazebo reference="caster_wheel">
    <mu1 value="0.0001"/>
    <mu2 value="0.0001"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Grey</material>
  </gazebo>

  <xacro:macro name="wheel" params="prefix reflect">

    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_dia/2}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_dia/2}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <joint name="base_to_${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <axis xyz="0 0 -1"/>
      <origin rpy="1.5708 0 0" xyz="0.03 ${wheel_separation/2*reflect} ${wheel_dia/2}"/>
    </joint>

    <gazebo reference="${prefix}_wheel">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Grey</material>
    </gazebo>

    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="base_to_${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>
    
  </xacro:macro>

  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>



</robot>
